// <auto-generated />
namespace OGameLikeV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class partie3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partie3));
        
        string IMigrationMetadata.Id
        {
            get { return "202003260928338_partie3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
